### ISSUE TITLE
Credential integration tests have a slight chance of a random failure.

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/imperative#26]
This keeps popping up with the latest being found in commit ceb416f that had a test fail.

### Test
```
Test: Integration / should update a password – Integration.Cli Profile Manager > Default Credential Management > Generic Success Scenarios
```

### Reason

```
Error: expect(received).toEqual(expected)
Expected value to equal:
""
Received:
"** Message: Remote error from secret service: org.freedesktop.DBus.Error.Failed: Couldn't create item: The secret was transferred or encrypted in an invalid way.
Command Error:
Unable to store the secure field \"username\" associated with the profile \"profile-name\" of type \"username-password\".
Error Details:
Couldn't create item: The secret was transferred or encrypted in an invalid way.
"
at Object.it (/home/jenkins/workspace/imperative_enhancement_21-KYTM3EI7KRAHUUAND4INIDN7D3FEUEAQJF3JTKK5HQKSAC2DZBTA/__tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts:156:31)
at Object.asyncFn (/home/jenkins/workspace/imperative_enhancement_21-KYTM3EI7KRAHUUAND4INIDN7D3FEUEAQJF3JTKK5HQKSAC2DZBTA/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
at resolve (/home/jenkins/workspace/imperative_enhancement_21-KYTM3EI7KRAHUUAND4INIDN7D3FEUEAQJF3JTKK5HQKSAC2DZBTA/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
at new Promise (<anonymous>)
at mapper (/home/jenkins/workspace/imperative_enhancement_21-KYTM3EI7KRAHUUAND4INIDN7D3FEUEAQJF3JTKK5HQKSAC2DZBTA/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
at promise.then (/home/jenkins/workspace/imperative_enhancement_21-KYTM3EI7KRAHUUAND4INIDN7D3FEUEAQJF3JTKK5HQKSAC2DZBTA/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
at <anonymous>
```

### Analysis

We believe that this issue is due to some form of a race condition in the underlying libraries attempting to access the keychain. That being said, there is no good way to debug this and attempt to fix. All we can really do is try stuff and hope to never see this issue again crossed_fingers

**Comment by AHumanFromCA** [comment]
Thinking about this even more, we could provide a dummy keytar library for use during integration tests and trust that the keytar library is tested by the developer. We could also have some manual testing to alleviate the issue.

**Comment by AHumanFromCA** [comment]
Happened again during a run of #90.

```
Test: Integration / should fail if keytar is not loaded on using profile handler – Integration.Cli Profile Manager > Default Credential Management > Missing keytar installation

Error: expect(received).toEqual(expected)
Expected value to equal:
""
Received:
"** Message: Remote error from secret service: org.freedesktop.DBus.Error.Failed: Couldn't create item: The secret was transferred or encrypted in an invalid way.
Command Error:
Unable to store the secure field \"username\" associated with the profile \"missing-keytar\" of type \"username-password\".
Error Details:
Couldn't create item: The secret was transferred or encrypted in an invalid way.
"
at Object.it (/home/jenkins/workspace/imperative_PR-90-EUGEWSEISD4W7XD2M6RS44YIZ62XVOYFQSZWZ3DBI4JUNIYCW27A/__tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts:272:31)
at Object.asyncFn (/home/jenkins/workspace/imperative_PR-90-EUGEWSEISD4W7XD2M6RS44YIZ62XVOYFQSZWZ3DBI4JUNIYCW27A/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
at resolve (/home/jenkins/workspace/imperative_PR-90-EUGEWSEISD4W7XD2M6RS44YIZ62XVOYFQSZWZ3DBI4JUNIYCW27A/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
at new Promise (<anonymous>)
at mapper (/home/jenkins/workspace/imperative_PR-90-EUGEWSEISD4W7XD2M6RS44YIZ62XVOYFQSZWZ3DBI4JUNIYCW27A/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
at promise.then (/home/jenkins/workspace/imperative_PR-90-EUGEWSEISD4W7XD2M6RS44YIZ62XVOYFQSZWZ3DBI4JUNIYCW27A/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
at <anonymous>
```

**Comment by gejohnston** [comment]
As the test environment has evolved, this behavior no longer occurs.
