### ISSUE TITLE
Random unit test failures for Profile IO

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/imperative#31]
The following unit tests can just fail in linux. Sometimes it will work, sometimes they will fail :/

```
 FAIL  packages/profiles/src/utils/__tests__/ProfileIO.test.ts
  ● Profile IO › should be able to read the meta file

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Object {
      "configuration": Object {
        "schema": Object {
          "description": "The simple blueberry configuration",
          "properties": Object {
            "tart": Object {
              "type": "boolean",
            },
          },
          "required": Array [
            "tart",
          ],
          "title": "The simple blueberry configuration",
          "type": "object",
        },
        "type": "blueberry",
      },
      "defaultProfile": Array [
        Object {
          "name": "sweet_blueberry",
          "type": "blueberry",
        },
      ],
    }
    + "undefined"
      
      at Object.it (packages/profiles/src/utils/__tests__/ProfileIO.test.ts:80:26)
          at new Promise (<anonymous>)
          at <anonymous>

  ● Profile IO › should throw an imperative error if an error occurs reading the meta file

    expect(received).toBeDefined()
    
    Expected value to be defined, instead received
      undefined
      
      at Object.it (packages/profiles/src/utils/__tests__/ProfileIO.test.ts:103:23)
          at new Promise (<anonymous>)
          at <anonymous>

  ● Profile IO › should be able to read a profile

    Profile IO Error: Error reading profile file ("/__tests__/__results__/data/.testHomeDir"). Error Details: Cannot create property 'type' on string 'undefined'
      
      at Function.readProfileFile (packages/profiles/src/utils/ProfileIO.ts:260:19)
      at Object.it (packages/profiles/src/utils/__tests__/ProfileIO.test.ts:357:47)
          at new Promise (<anonymous>)
          at <anonymous>

  ● Profile IO › should throw an imperative error if a profile IO read error occurs

    expect(string).toContain(value)
    
    Expected string:
      "Profile IO Error: Error reading profile file (\"/__tests__/__results__/data/.testHomeDir\"). Error Details: Cannot create property 'type' on string 'undefined'"
    To contain value:
      "Error Details: IO ERROR!"
      
      at Object.it (packages/profiles/src/utils/__tests__/ProfileIO.test.ts:380:31)
          at new Promise (<anonymous>)
          at <anonymous>
```

**Comment by gejohnston** [comment]
As the test environment has evolved, this behavior no longer occurs.
