### ISSUE TITLE
Logger fails when logging an error message: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by plavjanik** [zowe/imperative#449]
It seems that the logger fails when an element of the stack trace does not have a file name.

```
TypeError: Cannot read property 'indexOf' of null
at Logger.getCallerFileAndLineTag (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/logger/src/Logger.js:325:53)
at Logger.debug (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/logger/src/Logger.js:175:40)
at Logger.timerified debug (<anonymous>)
at /u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/AbstractRestClient.js:108:26
at new Promise (<anonymous>)
at ZosmfRestClient.request (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/AbstractRestClient.js:70:16)
at Function.putExpectString (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:210:34)
at Function.<anonymous> (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:68:37)
at Generator.next (<anonymous>)
at /u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:18:71
```

This seems like the line that is causing the problem: https://github.com/zowe/imperative/blob/master/packages/logger/src/Logger.ts#L357

**Comment by plavjanik** [comment]
This problem occurs while running https://github.com/plavjanik/zowe-zosmf-perftest-driver outside of our systems. We do not know what part of its code is causing it yet since the original error is not printed because of this problem.

**Comment by dkelosky** [comment]
To narrow this down a bit, can you try adding this to the begging of your file?

https://github.com/dkelosky/use-zowe-cli-package/blob/master/src/index.ts#L6

**Comment by dkelosky** [comment]
To narrow this down a bit, can you try adding this to the beginning of your file?

https://github.com/dkelosky/use-zowe-cli-package/blob/master/src/index.ts#L6

**Comment by plavjanik** [comment]
Thank you. I will try it.

It happens on Node 8 on z/OS. It does not happen on Node 12.

This is the full stack trace:

```
TypeError: Cannot read property 'indexOf' of null
    at Logger.getCallerFileAndLineTag (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/logger/src/Logger.js:325:53)
    at Logger.debug (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/logger/src/Logger.js:175:40)
    at Logger.timerified debug (<anonymous>)
    at /u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/AbstractRestClient.js:108:26
    at new Promise (<anonymous>)
    at ZosmfRestClient.request (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/AbstractRestClient.js:70:16)
    at Function.putExpectString (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:210:34)
    at Function.<anonymous> (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:68:37)
    at Generator.next (<anonymous>)
    at /u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:14:12)
    at Function.putExpectJSON (/u/tnzsys/zowe-test/node_modules/@zowe/imperative/lib/rest/src/client/RestClient.js:67:16)
    at Function.<anonymous> (/u/tnzsys/zowe-test/node_modules/@zowe/cli/lib/zosjobs/src/api/SubmitJobs.js:118:43)
    at Generator.next (<anonymous>)
    at /u/tnzsys/zowe-test/node_modules/@zowe/cli/lib/zosjobs/src/api/SubmitJobs.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/u/tnzsys/zowe-test/node_modules/@zowe/cli/lib/zosjobs/src/api/SubmitJobs.js:14:12)
    at Function.submitJclCommon (/u/tnzsys/zowe-test/node_modules/@zowe/cli/lib/zosjobs/src/api/SubmitJobs.js:97:16)
    at Function.submitJcl (/u/tnzsys/zowe-test/node_modules/@zowe/cli/lib/zosjobs/src/api/SubmitJobs.js:77:27)
    at Object.action (/u/tnzsys/zowe-test/node_modules/@zowedev/zztop/lib/index.js:118:56)
    at Zztop.userActivity (/u/tnzsys/zowe-test/node_modules/@zowedev/zztop/lib/index.js:155:45)
    at async Promise.all (index 3)
    at async Zztop.run (/u/tnzsys/zowe-test/node_modules/@zowedev/zztop/lib/index.js:221:34)
    at async Zztop._run (/u/tnzsys/zowe-test/node_modules/@oclif/command/lib/command.js:43:20)
```

**Comment by plavjanik** [comment]
@JirkaAichler
