### ISSUE TITLE
Bug in UpdateImpConfig.js (?)

### ISSUE THREAD

**Issue by Yuliya-Kirkorava** [zowe/imperative#859]
Hi,
I got an error when I tried to install @zowe/zos-make-for-zowe-cli:
![image](https://user-images.githubusercontent.com/96059205/181564913-f5be2be3-de3a-4ae9-acb6-0114c92e06e6.png)

In the Imperative.log file there are some additional messages:
msg: 'Install Failed',
      causeErrors: ImperativeError: profiles is not iterable
          at Object.<anonymous> (C:\Users\Kirkorava_Y\AppData\Roaming\nvm\v18.7.0\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\imperative\src\plugins\utilities\npm-interface\install.js:134:19)
          at Generator.next (<anonymous>)
          at fulfilled (C:\Users\Kirkorava_Y\AppData\Roaming\nvm\v18.7.0\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\imperative\src\plugins\utilities\npm-interface\install.js:15:58) {
        mDetails: {
          msg: 'profiles is not iterable',
          causeErrors: TypeError: profiles is not iterable
              at UpdateImpConfig.addProfiles **(C:\Users\Kirkorava_Y\AppData\Roaming\nvm\v18.7.0\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\imperative\src\UpdateImpConfig.js:54:40)**
              at Object.<anonymous> (C:\Users\Kirkorava_Y\AppData\Roaming\nvm\v18.7.0\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\imperative\src\plugins\utilities\npm-interface\install.js:127:51)
              at Generator.next (<anonymous>)
              at fulfilled (C:\Users\Kirkorava_Y\AppData\Roaming\nvm\v18.7.0\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\imperative\src\plugins\utilities\npm-interface\install.js:15:58)
        },
        mMessage: 'profiles is not iterable'

I try to change this plugin to run it with Zowe V2,  and seems UpdateImpConfig.js is a potential place for the bug.

Thanks!

**Comment by t1m0thyj** [comment]
What is the command you used to install the zos-make plug-in?

**Comment by Yuliya-Kirkorava** [comment]
I cloned this project and use npm script "installPlugin": 
"npm install && npm run clean && npm run build && zowe plugins install  ." 
But the same error was when I used :
zowe plugins install @zowe/zos-make-for-zowe-cli@latest
from README file.

**Comment by t1m0thyj** [comment]
For the zos-make plug-in, the `master` branch on GitHub and `@latest` tag on NPM are for the Zowe v1 version.

To use the Zowe v2 beta or prerelease version of the plug-in, you'd want to install either from the `@next` tag on NPM:
`zowe plugins install @zowe/zos-make-for-zowe-cli@next`

Or to install from source, use the `next` branch:
`git checkout next && npm install && npm run build && zowe plugins install .`

**Comment by Yuliya-Kirkorava** [comment]
![image](https://user-images.githubusercontent.com/96059205/181590516-a88291f0-b6e7-4dc2-83a5-4933d800809d.png)

**Comment by t1m0thyj** [comment]
Thanks for reporting 🙂 I investigated this some more and found there is a bug in Imperative and Zowe CLI that prevents you from installing plug-ins that don't define profiles.

**Comment by t1m0thyj** [comment]
This should be fixed in the latest version of Zowe CLI (7.4.1).

To update your Zowe CLI version, you can reinstall with the command `npm install -g @zowe/cli@zowe-v2-lts`

Then you should be able to install the zos-make plug-in without any errors (there may still be warnings but that is expected).

**Comment by Yuliya-Kirkorava** [comment]
After reinstallation @zowe/cli the plugin was installed without any problems! 
Thank you for fixing this problem.
