### ISSUE TITLE
Failing unit tests present in master on Windows

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/imperative#92]
I ran `npm run test:unit` today in one of my branches and found that these tests were failing for me on windows:

```
FAIL  packages\imperative\__tests__\plugins\utilities\npm-interface\uninstall.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at patch (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:27:18)
      at node_modules/npm/lib/npm.js:19:13
      at Object.<anonymous> (node_modules/npm/lib/npm.js:490:3)

 FAIL  packages\imperative\__tests__\plugins\utilities\npm-interface\update.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at patch (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:27:18)
      at node_modules/npm/lib/npm.js:19:13
      at Object.<anonymous> (node_modules/npm/lib/npm.js:490:3)

 FAIL  packages\imperative\__tests__\plugins\utilities\npm-interface\install.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at patch (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:27:18)
      at node_modules/npm/lib/npm.js:19:13
      at Object.<anonymous> (node_modules/npm/lib/npm.js:490:3)

Summary of all failing tests
 FAIL  packages\imperative\__tests__\plugins\utilities\npm-interface\uninstall.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at patch (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:27:18)
      at node_modules/npm/lib/npm.js:19:13
      at Object.<anonymous> (node_modules/npm/lib/npm.js:490:3)

 FAIL  packages\imperative\__tests__\plugins\utilities\npm-interface\update.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at patch (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:27:18)
      at node_modules/npm/lib/npm.js:19:13
      at Object.<anonymous> (node_modules/npm/lib/npm.js:490:3)

 FAIL  packages\imperative\__tests__\plugins\utilities\npm-interface\install.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at patch (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/npm/node_modules/graceful-fs/graceful-fs.js:27:18)
      at node_modules/npm/lib/npm.js:19:13
      at Object.<anonymous> (node_modules/npm/lib/npm.js:490:3)


Test Suites: 3 failed, 74 passed, 77 total
```

So I switched to master to confirm if it was me and I unfortunately saw the same errors. Looking at the error it looks to have been introduced by #75. @nurra01 could you take a look at this and get a fix to master ASAP?

Interesting that you do no see this behavior on the build machine, that's why I didn't catch it. I just made the assumption that you were developing on a windows machine so you would be running a sanity check on windows, I should have run the tests as well on my machine...my bad :slightly_frowning_face:

**Comment by AHumanFromCA** [comment]
Hey @nurra01,

So are you saying that these messages are expected and the tests are still operating as expected?

**Comment by nurra01** [comment]
@AHumanFromCA yes

**Comment by AHumanFromCA** [comment]
Updating node from 10.6 to 10.9 fixed the issue, closing.
